server:
  servlet:
    context-path: /seller
  port: 8084

#jsonrpc日志打印
logging:
  level:
    com.googlecode.jsonrpc4j: debug

#自定义rpc服务数据
rpc:
  server:
    scanPackage: com.szjz.api  #对外服务接口所在包路径
    url: http://localhost:8083/manager  #服务端baseUrl

#缓存类型
spring:
  cache:
    type: hazelcast

  #activemq
  activemq:
    broker-url: tcp://localhost:61616  #服务地址
    packages:
      trust-all: true  #信任所有包，所有的包都可以接受消息

  datasource:
    #多数据源时将url 改为 jdbc-url
    backup:  #备份库
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql:///financial-backup?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false

    primary: #主库
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql:///financial?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false


#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql:///financial?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource

    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
#热部署
  devtools:
    restart:
      enabled: true

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        max_fetch_depth: 1
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
    show-sql: true


#配置当前模块的swagger
swagger:
  groupName: seller
  basePackage: com.szjz.seller.controller