spring:


  datasource:
    username: root
    password: root
    url: jdbc:mysql:///financial?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  #返回客户端的时间格式
  jackson:
    #java.text.SimpleDateFormat  #19-6-19 上午10:15
    date-format: yyyy-MM-dd HH:mm:ss
    #东八区
    time-zone: GMT+8

server:
  port: 8081
  servlet:
    context-path: /manager


#配置当前模块的swagger
swagger:
  groupName: manager
  basePackage: com.szjz.manager.controller